import { Recursive } from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ToastContainer } from 'react-toastify';


const recursive = Recursive({ subsets: ['latin'] })

export const metadata = {
  title: "Pind Pind Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={recursive.className}>
        <Navbar />
        <ToastContainer position="top-right" theme="light" autoClose={3000}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
